spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
#    url: ${JDBC_DATABASE_URL}
#    url: "jdbc:postgresql://localhost:5432/mytest"
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mytest}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:9111}
    driverClassName: org.postgresql.Driver

  auth0:
    audience: "https://social-mood-track-backend.herokuapp.com"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://nullcorp.eu.auth0.com/"

  autoconfigure:
    #exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    #exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration